site_name: ECE-IoT Prototyping
nav:
  - Home: index.md
  - Tutorials:
      - C++: tutorials/cpp-coding-style.md
      - Git: tutorials/git-commit-style.md
      - Prototyping Guide: tutorials/prototyping-guide.md
  - Documentation:
      - AWS:
          - MQTT: src/aws/mqtt/doc-mqtt.md
      - Arduino:
          - Arduino IoT Cloud: src/arduino/arduino-iot-cloud/doc-aic-overview.md

repo_url: https://github.com/ECE-IoT/Prototyping

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - git-revision-date
  - mkdocstrings

markdown_extensions:
  - footnotes
  - def_list
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
