site_name: ECE-IoT Prototyping
nav:
  - Home: index.md
  # - Tutorials:
  #     - C++: tutorials/cpp-coding-style.md
  #     - Git: tutorials/git-commit-style.md
  #     - Prototyping Guide: tutorials/prototyping-guide.md
  # - Documentation:
  #     - AWS:
  #         - Identity and Access Management: src/aws/aws-iam.md
  #         - CLI: src/aws/aws-cli.md
  #     - Arduino:
  #         - Arduino IoT Cloud:
  #             - Getting started: src/arduino/arduino-iot-cloud/doc-aic-getting-started.md
  #             - Overview: src/arduino/arduino-iot-cloud/doc-aic-overview.md
  #             - Compatible boards: src/arduino/arduino-iot-cloud/doc-aic-boards.md
  #             - Example: src/arduino/arduino-iot-cloud/doc-aic-example.md
  #     - Hardware:
  #         - Temperature and Humidity:
  #             - DHT11: src/hardware/temperature-humidity/dht11.md
  #             - Soil Sensor: src/hardware/temperature-humidity/soil-sensor.md
  #         - Wind Velocity:
  #             - Anemometer: src/hardware/wind-velocity/Anemometer.md
  #         - Gas:
  #             - CCS881: src/hardware/CO2/CCS881.md
  #         - Luminosity:
  #             - VEML7700: src/hardware/brightness/VEML7700.md

repo_url: https://github.com/ECE-IoT/Prototyping

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - git-revision-date
  - mkdocstrings
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(window.localStorage.getItem('/.__palette')).index == 1) ? 'dark' : 'light'

markdown_extensions:
  - footnotes
  - admonition
  - def_list
  - attr_list
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
