site_name: Prototyping
nav:
  - Home: https://ece-iot.github.io/Prototyping/

repo_url: https://github.com/ECE-IoT/Prototyping

theme:
  name: material
  language: en
  logo: docs/assets/logo.png
  favicon: docs/assets/logo.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
