#!/usr/bin/env python3

"""
Created: 10/19/21
by: Tim Schmid

Automatically update the src_filter in platformio.ini
"""

import os
import argparse
import configparser

envs = ["aws", "arduino"]
env_config = configparser.ConfigParser()
aws = 'code/aws'
arduino = 'code/arduino'

BASE_PATH = os.path.join(os.path.dirname(
    os.path.abspath(__file__)), os.pardir)
CONFIG_PATH = os.path.join(BASE_PATH, 'config', 'env', 'env.ini')

def checkFile():
    if not os.path.exists(CONFIG_PATH):
      print("No file detected. A new file will be created \n")
      with open(CONFIG_PATH, 'w') as env:
        env_config.read(CONFIG_PATH)

        env_config.add_section("common")

        with open(CONFIG_PATH, 'w') as f:
          env_config.write(f)

        print("New file created \n")

def setEnvironment():
  parser = argparse.ArgumentParser()
  parser.add_argument("env", help="Title of the desired environment (aws, arduino)")
  args = parser.parse_args()

  env_config.read(CONFIG_PATH)

  if args.env == envs[0]:
    env_config["common"]["src_dir"] = aws
  elif args.env == envs[1]:
    env_config["common"]["src_dir"] = arduino

  with open(CONFIG_PATH, 'w') as f:
    env_config.write(f)

  print(f"The environment {args.env} has been set \n")


if __name__ == "__main__":
  print(f"\033[90m{__doc__}\033[0m", end="\n")
  checkFile()
  setEnvironment()


    

