#!/bin/bash 

local_branches() {
  git for-each-ref --format="%(refname:short)" refs/heads
}

# Returns the name of the current branch
current_branch() {
  git symbolic-ref --short HEAD
}

saved_branch=$(current_branch)

[[ "${saved_branch}" != "master" ]] && git checkout "master"
git pull

for branch in $(local_branches); do
  if [[ "${branch}" != "master" ]]; then
      if [[ "${branch}" != "gh-pages" ]]; then  
      echo --------------------------------------------------------
      git checkout "${branch}"
      echo 
      echo Try to merge master into "${branch}":
      git merge "master"
      echo 
      echo Try to push "${branch}" to origin:
      git push
      echo --------------------------------------------------------
      fi
  fi
done

echo
[[ "${saved_branch}" != "$(current_branch)" ]] && git checkout "${saved_branch}"