// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include "ArduinoIoTCloud.h"
#include "Arduino_ConnectionHandler.h"
#include "arduino_secrets.h"

// The THING_ID can be found in the sharepoint fodler under: Dateien\Administration\Arduino IoT Cloud\Wifi and thing id.txt
const char THING_ID[] = "";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onMkr1010LedChange();

float mkr1010_humid;
bool mkr1010_led;
float mkr1010_temp;

void initProperties()
{
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(mkr1010_humid, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(mkr1010_led, READWRITE, ON_CHANGE, onMkr1010LedChange);
  ArduinoCloud.addProperty(mkr1010_temp, READ, 1 * SECONDS, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
